{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.pvtitov",
    "module": "noserver",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "noserver-1.0.0.aar",
          "url": "noserver-1.0.0.aar",
          "size": 72892,
          "sha512": "3c8edff2e25f2c3a784ce71a0aa4d002ca1bf905ea415bed97a7e094cf41385ddd8e8132a215bce9c378da8a414ff4d28386f2a7cdaee5bfa17cf4428e81f2d3",
          "sha256": "66ae816ef9a1e3ff6512c3fd2bb813898e11a6cb0e538ef85b4beb8734e77a3a",
          "sha1": "abe8f376ca418088f86a57e6f7c33b7768a2651b",
          "md5": "272d76788b1a5910a27d17ba99d38170"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "21.4.0"
          }
        },
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.6.0-beta03"
          }
        },
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.6.0-beta03"
          }
        },
        {
          "group": "com.google.android.libraries.identity.googleid",
          "module": "googleid",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.apis",
          "module": "google-api-services-drive",
          "version": {
            "requires": "v3-rev20240509-2.0.0"
          }
        },
        {
          "group": "com.google.api-client",
          "module": "google-api-client-android",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "noserver-1.0.0.aar",
          "url": "noserver-1.0.0.aar",
          "size": 72892,
          "sha512": "3c8edff2e25f2c3a784ce71a0aa4d002ca1bf905ea415bed97a7e094cf41385ddd8e8132a215bce9c378da8a414ff4d28386f2a7cdaee5bfa17cf4428e81f2d3",
          "sha256": "66ae816ef9a1e3ff6512c3fd2bb813898e11a6cb0e538ef85b4beb8734e77a3a",
          "sha1": "abe8f376ca418088f86a57e6f7c33b7768a2651b",
          "md5": "272d76788b1a5910a27d17ba99d38170"
        }
      ]
    }
  ]
}
